default:
  # image: ${CI_REGISTRY}/devops/images/usgs/python:3.9
  image: ${DEVOPS_REGISTRY}usgs/python:3.9
  tags:
    - development

stages:
  - test
  - build

run tests:
  stage: test
  script:
    - pip install --no-warn-script-location -e .[test]
    - export PATH="/home/usgs-user/.local/bin:$PATH"
    - pwd
    - pytest -rx --cov=src/gmprocess --cov-report xml:coverage.xml --cov-report term
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

run build:
  script:
    - pip install .[build]
    - export PATH="/home/usgs-user/.local/bin:$PATH"
    - python -m build
    - python -m twine upload dist/*
  stage: build
  rules:
    # Run this job when a tag is created manually
    - if: $CI_COMMIT_TAG
