default:
  # image: ${CI_REGISTRY}/devops/images/usgs/python:3.9
  image: ${DEVOPS_REGISTRY}usgs/python:3.9
  tags:
    - development
  before_script:
    - python --version
    - export PATH="/home/usgs-user/.local/bin:$PATH"
    - mini_conda_url=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - curl -L $mini_conda_url -o miniconda.sh
    - bash miniconda.sh -f -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - conda install -c conda-forge -y tree make

stages:
  - test
  - build
  - docs

run tests:
  stage: test
  script:
    - uname -a
    - pip install -e .[test]
    - pytest -rx .
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == 'merge_request_event'

run tests and coverage:
  stage: test
  script:
    - pip install -e .[test]
    - pytest -rx --cov=src/gmprocess --cov-report xml:coverage.xml --cov-report term
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == 'merge_request_event'


run upload pypi:
  stage: build
  script:
    - pip install .[build]
    - python -m build
    - python -m twine upload dist/*
  rules:
    # Run this job when a tag is created manually
    - if: $CI_COMMIT_TAG

pages:
  stage: docs
  script:
    - pip install -e .[doc]
    - cd doc_source
    - bash makedocs.sh
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - docs
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
