default:
  # image: ${CI_REGISTRY}/devops/images/usgs/python:3.9
  image: ${DEVOPS_REGISTRY}usgs/python:3.9
  tags:
    - development

stages:
  - test
  - build

run tests:
  stage: test
  script:
    - pip install .[test]
    - export PATH="/home/usgs-user/.local/bin:$PATH"
    - pytest --cov=. --cov-report=xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

run build:
  script:
    - pip install .[build]
    - python -m build
    - python3 -m twine upload dist/*
  stage: build
  rules:
    # Run this job when a tag is created manually
    - if: $CI_COMMIT_TAG
