version : 2

build:
  image: latest

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

conda:
  environment: requirements.txt

sphinx:
  configuration: docs/conf.py

