name: gmprocess
channels:
- conda-forge
dependencies:
- cython
- gcc
- ipython
- jupyter
- lxml
- matplotlib
- numpy>=1.14
- openpyxl
- obspy
- pytest
- pytest-cov
- python=3.5
- pyyaml
- requests
- vcrpy
