remote_theme: pmarsceill/just-the-docs
title: Ground-Motion Processing Software
baseurl: /groundmotion-processing
#search_enabled: true
aux_links:
    "GitHub repository":
      - "//github.com/usgs/groundmotion-processing"

plugins:
  - jekyll-seo-tag
  
