remote_theme: baagaard-usgs/just-the-docs
title: Ground-Motion Processing Software
baseurl: /groundmotion-processing
aux_links:
    "GitHub repository":
      - "//github.com/usgs/groundmotion-processing"

color_scheme: usgs_lightbg
heading_anchors: false
search_enabled: true

title_image: images/USGSsimple.png
software_version: 1.0.4
